version: "3"

networks:
  traefik-public:
    external: true

volumes:
  ineo-sync-data:
    driver: local

services:
  ineo-service:
    image: ghcr.io/knaw-huc/ineo_service:0.5
    container_name: service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service.rule=Host(`ineo-service.sd.di.huc.knaw.nl`)"
      - "traefik.http.routers.service.entrypoints=http"
      - "traefik.http.services.service.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    environment:
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_INDEX: ${ELASTICSEARCH_INDEX}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      FRONTEND_HOST: ${FRONTEND_HOST}
  ineo-sync:
    image: registry.diginfra.net/tsd/ineo-sync:0.9
    container_name: ineo-sync
    volumes:
      - ineo-sync-data:/app/data
    restart: unless-stopped
    networks:
      - traefik-public

  basex:
    image: registry.diginfra.net/tsd/basex:latest
    container_name: basex
    restart: unless-stopped
    volumes:
      - ineo-sync-data:/data
      - ./basex_data:/basex/dbdata
    networks:
        - traefik-public

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - traefik-public