for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}" 
return
  if ($i.applicationCategory instance of array) then 
    for $item in $i."applicationCategory"[]
    return
      if ($item."skos:prefLabel" instance of array) then
        for $label in $item."skos:prefLabel"[]
        where $label."@language" eq "en"
        return [$label."@value"]
      else if ($item."skos:prefLabel"."@language" eq "en")
      then [$item."skos:prefLabel"."@value"]
      else ()
  else if ($i.applicationCategory instance of string) then [$i.applicationCategory]  
  else ()




