for $i in json-file("/data/codemeta.jsonl", 10)
where $i.identifier eq "{ID}"
return
  if ($i.applicationCategory instance of array) then 
    for $item in $i."applicationCategory"[]
    where starts-with($item."@id", "http")
    return 
      $item."@id"
  else ()