for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
  if ($i.applicationCategory instance of array) then 
    for $item in $i."applicationCategory"[]
    where starts-with($item."@id", "http")
    return ([
      $item."@id",
      $item."skos:broader"."@id"]
    )
  else ()