let $results := (
  for $i in json-file("{JSONL}", 10)
  where $i.identifier eq "{ID}" 
return (
    for $author in $i.author[]
    let $title :=
      if (exists($author.affiliation) and ($author.affiliation.name instance of array)) then
          for $name in $author.affiliation.name[]
          where $name."@language" eq "en" return
                 $author."givenName" || " " || $author."familyName" || ", " || $name."@value"

      else if (exists($author.affiliation) and ($author.affiliation.name instance of string)) then
        $author."givenName" || " " || $author."familyName" || ", " || $author.affiliation.name
      else if (exists($author.affiliation) and ($author.affiliation.legalName instance of string)) then
        $author."givenName" || " " || $author."familyName" || ", " || $author.affiliation.legalName
else if (exists($author.affiliation) and ($author.affiliation instance of array)) then
for $name in $author.affiliation[[1]]
return $author."givenName" || " " || $author."familyName" || ", " || $name.name

      else
        $author."givenName" || " " || $author."familyName"
    return {
      "title": $title,
      "link": (
if (exists($author."url")) then
          $author."url"      
else if (exists($author."sameAs")) then
          $author."sameAs"
        else if (exists($author."@id") and not(starts-with($author."@id", "https://tools.clariah.nl"))) then
          $author."@id"
        else ()
      )
    }
  )
)

let $uniqueValues :=
  for $result in distinct-values(
    for $r in $results
    return fn:concat(
      $r."title",
      "|",
      string-join(
        for $link in $r."link"
        return if ($link instance of xs:string) then $link else (),
        "|"
      )
    )
  )
  let $title := fn:substring-before($result, "|")
  let $link := fn:substring-after($result, "|")
  group by $title
    return {
    "title": $title,
    "link": (
      if ($link = "") then
        ()
      else
        $link
    )
  }

return [$uniqueValues]