let $results := (for $i in json-file("{JSONL}", 10) 
where $i.identifier eq "{ID}"

return (
  for $author in $i.author[]
  return {
    "title": $author."givenName" || " " || $author."familyName",
    "link": [$author."url", $author."email", null][[1]]
  },
  for $contributor in $i.contributor[]
  return {
    "title": $contributor."givenName" || " " || $contributor."familyName",
    "link": [$contributor."url", $contributor."email", null][[1]]
  }
)
)

let $uniqueValues :=
  for $result in distinct-values(
    for $r in $results
    return fn:concat(
    $r."title", 
    "|", 
    string-join(
        for $link in $r."link"
        return if ($link instance of xs:string) then $link else (),
        "|"
    )
)

  )
  return {
    "title": fn:substring-before($result, "|"),
    "link": fn:substring-after($result, "|")
  }
  
return [$uniqueValues]