(: For each matching item, this query constructs an array containing objects with two fields:

"title": It extracts a substring from the codeRepository field by taking the content between "://" and the first "/" after that. This effectively isolates the domain or service name from the URL.
For instance: https://github.com/knaw-huc/huc-cmdi-app - > github.com
"link": It directly assigns the codeRepository field as the link.:)


for $i in json-file("{JSONL}", 10) 
where $i.identifier eq "{ID}" 
return [
  {
    "title": substring-before(substring-after($i.codeRepository, "://"), "/"),
    "link": $i.codeRepository
  }
]
