for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
  if ($i.applicationCategory instance of array) then
    let $filteredItems :=
      for $item in $i.applicationCategory[]
      return
        if ($item instance of xs:string) then
          xs:string($item)
        else ()
    return [$filteredItems]
  else ()
