(: This query focuses on the consumed and produced data formats within the isSourceCodeOf of codemeta.
It first checks the structure of the consumesData and producesData fields within the isSourceCodeOf.
If these fields are arrays, it iterates through each item to extract the encodingFormat.
If they are objects, it directly retrieves the encodingFormat.
It constructs a list of consumed and produced data formats ($consumesFormats and $producesFormats respectively (e.g. plain/text)).
The values are then split by the "/" delimiter, ensuring uniqueness in the format names (e.g. plain, text). :)



let $results := (
  for $i in json-file("{JSONL}", 10)
  where $i.identifier eq "{ID}"

  return
    let $consumesFormats :=
      if ($i.isSourceCodeOf.consumesData instance of array) then
        for $data in $i.isSourceCodeOf.consumesData[]
        return
            $data.encodingFormat
      else if ($i.isSourceCodeOf.consumesData instance of object) then
        $i.isSourceCodeOf.consumesData.encodingFormat
      else
        ()
    


let $producesFormats :=
      if ($i.isSourceCodeOf.producesData instance of array) then
        for $data in $i.isSourceCodeOf.producesData[]
        return
            $data.encodingFormat
      else if ($i.isSourceCodeOf.producesData instance of object) then
        $i.isSourceCodeOf.producesData.encodingFormat
      else
        ()
    return ($consumesFormats, $producesFormats)
)



let $splitValues :=
  for $value in $results
  for $component in tokenize($value, "/")
  return $component

return [distinct-values($splitValues)]
