for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return [
  {
    "title": (
      if ($i.producer."name"."@value")
      then $i.producer."name[@language == 'en']"."@value"
      else $i.producer."name"
    ),
    "link": $i.producer."url"
  }
]



