(: This script focuses on extracting provider names and associated URLs from the "isSourceCodeOf" field, 
ensuring that for arrays of names, it selects the English name with the respective URL. :)



let $results := (
  for $i in json-file("{JSONL}", 10) 
  where $i.identifier eq "{ID}"
  return
  if ($i.isSourceCodeOf.provider.name instance of string) 
  then [{"title": $i.isSourceCodeOf.provider.name, "link": $i.isSourceCodeOf.provider.url}]
  else [
    for $name in $i.isSourceCodeOf.provider.name[]
    where $name."@language" eq "en"
    return {"title": $name."@value", "link": $i.isSourceCodeOf.provider.url}
  ]
)

return $results
