for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
if ($i.softwareHelp instance of object) then [{"title": $i.softwareHelp."name", "link": $i.softwareHelp."url"}]
else if ($i.softwareHelp instance of array) then [
for $item in $i.softwareHelp[]
return {"title": $item."name", "link": $item."url"}]
else "null"