(:
This query maps a URL to the link field in the template for INEO. The link field maps to the "Go to resource" button in INEO.

It first checks if there is a targetProduct field for WebApplication and WebSite (e.g. for mediasuite) or SoftwareLibrary (for alud) in the codemeta. If there is, then it takes the url of the targetProduct. 
If the tool is not a WebApplication or a WebSite, it checks for a 'url' root field. It checks if the value of url is an object (dictionary) 
or a string with a 'url' property in the codemeta file.

If there is not a url key in the codemeta (e.g. for alud) it returns the value of the codeRepository :)


for $i in json-file( "{JSONL}", 10)
where $i.identifier eq "{ID}"
return
if (exists($i.targetProduct)) then
        
if ($i.targetProduct."@type" eq "WebApplication" or $i.targetProduct."@type" eq "WebSite") then $i.targetProduct.url

else if (exists($i.targetProduct) and $i.targetProduct instance of array) then
for $product in $i.targetProduct[]
where ($product."@type" eq "SoftwareLibrary"  or $product."@type" eq "WebApplication" or $product."@type" eq "WebSite" )
              return
                    if (exists($product.url)) then
                        $product.url
                    else if ($i.url instance of object and exists($i.url.url)) then
        $i.url.url

else $i.codeRepository


else($i.url)

else($i.url)




