(: This query operates on a JSONL file, limiting results to 10 items and filtering based on a specified identifier defined by template.py. 
It checks if the applicationCategory field in the codemeta is an array. If it is, it iterates through each item in the array and retrieves those whose @id field starts with "http", 
returning an array of these @id values. If applicationCategory is not an array, it returns an empty result. :)




for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
  if ($i.applicationCategory instance of array) then 
    for $item in $i."applicationCategory"[]
    where starts-with($item."@id", "http")
    return ([
      $item."@id"]
    )
  else ()