(: If applicationCategory is an array, it creates a variable $filteredItems that stores a filtered set of items.
It iterates through each item in applicationCategory[].
If an item is a string, it converts it to a string type and includes it in the $filteredItems array. 
This query maps the applicationCategory to researchDomains.:)



for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
  if ($i.applicationCategory instance of array) then
    let $filteredItems :=
      for $item in $i.applicationCategory[]
      return
        if ($item instance of xs:string) then
          xs:string($item)
        else ()
    return [$filteredItems]
  else ()
