(: This query identifies whether the "@id" field in the codemeta contains https://tools.clariah.nl,
and if so, it returns an array with the string "Tools"; otherwise, it returns an empty result. :)


for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
let $id := $i."@id"
return if (contains($id, "https://tools.clariah.nl")) then ["Tools"] else ()