(: This query extracts information from the "softwareHelp" field, ensuring proper handling for both object (dicionary) and array structures within it. 
If the field is an object, it extracts the name and URL. 
If it's an array, it extracts multiple sets of name and URL pairs, and if none of these structures match, it returns nothing. :) 



for $i in json-file("{JSONL}", 10)
where $i.identifier eq "{ID}"
return
if ($i.softwareHelp instance of object) then [{"title": $i.softwareHelp."name", "link": $i.softwareHelp."url"}]
else if ($i.softwareHelp instance of array) then [
for $item in $i.softwareHelp[]
return {"title": $item."name", "link": $item."url"}]
else ()