networks:
  traefik-public:
    external: true


services:
  python-run:
    build: .
    image: ineo-sync:latest
    container_name: ineo-sync
    volumes:
      - ./:/src
    restart: unless-stopped
    networks:
      - traefik-public

  basex:
    image: registry.diginfra.net/tsd/basex:latest
    container_name: basex
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./basex_data:/basex/dbdata
    ports:
      - "8082:8080"
    networks:
      - traefik-public
