version: "3"

services:
  python-run:
    build: .
    image: ineo-sync:0.1
    container_name: ineo-sync
    volumes:
      - ./:/src
    restart: unless-stopped

  rumbledb:
    image: rumbledb/rumble:latest
    container_name: rumbledb
    volumes:
      - ./data:/data 
    restart: unless-stopped
    command: ["serve", "-p", "8001", "-h", "0.0.0.0"]
    ports:
      - 8001:8001
    depends_on:
      - python-run
  