version: "3"

services:
  python-run:
    build: .
    image: ineo-sync:latest
    container_name: ineo-sync
    volumes:
      - ./data_swap:/data
#      - ./:/src
    restart: unless-stopped

  rumbledb:
    image: rumbledb/rumble:latest
    container_name: rumbledb
    volumes:
      - ./data_swap:/data
    restart: unless-stopped
    command: ["serve", "-p", "8001", "-h", "0.0.0.0"]
    ports:
      - 8001:8001
    depends_on:
      - python-run
  