(: This query maps either the "accessInfo" or "license" field based on their existence to INEO's Access. 
The "title" is taken from the first element ($desc[[1]]).
The "link" is determined based on the following conditions:
1. If the first element contains "http:", it takes that link (e.g.http://www.apache.org/licenses/LICENSE-2.0 id: "http_58__47__47_hdl.handle.net_47_10032_47_c632814b08cafbbdefed5de13de6bdb0")
2. If the first element contains "OPEN" and the second element contains "http:", it sets the link to the second element ($desc[[2]]):
This second condition is valid for cases such as ["OPEN_ACCESS","http://creativecommons.org/publicdomain/zero/1.0" (id: oai_58_easy.dans.knaw.nl_58_easy-dataset_58_114649)]

Otherwise, it sets the link to () (an empty sequence). :)



let $access := (
    for $i in json-file("{JSONL}", 10)
where $i.id eq "{ID}"

    return 
        if (exists($i.accessInfo))
        then $i.accessInfo
        else $i.license
)

let $containsOpenAccess := 
    for $item in $access
    return
   {
            "title": $item[[1]],
            "link": if (contains($item[[1]], "http:")) then $item[[1]] 

else if (contains($item[[1]], "OPEN")) then $item[[2]] 

else ()
        }

return [$containsOpenAccess]
