let $description := (
    for $i in json-file("/data/datasets copy.jsonl", 10)
    where $i.id eq "https_58__47__47_hdl.handle.net_47_1839_47_00-0000-0000-0009-426C-B"
    return $i.description
)

let $english := (
    for $item in $description[]
    where contains($item, "{code:eng}") or contains($item, "{code:und}") or contains($item, "{code:lbe}")
    return $item
)

let $mergedString := string-join($english, " ")


return $mergedString